- name: Demo on loading file
  hosts: all
  tasks:
    - name: Print Hello World
      ansible.builtin.debug:
        msg: Hello Ansible World
    - name: Include Universe File
      ansible.builtin.include_tasks:
        file: universe.yml
