- name : Print Parameter from Parameter Store
  hosts : localhost
  connection : local
  tasks :
    - name : Print Parameter
      ansible.builtin.debug:
        msg : parameter - {{lookup ('amazon.aws_ssm','test.test',region='us-east-1')}}